### ISSUE TITLE
Selective Secret Storage with Expiration?

### ISSUE THREAD

**Issue by isugimpy** [af-inet/kubestash#6]
Before writing this up, just want to say I love where you've gone with this project.

I started earlier today writing up what is effectively a competitor to this package, and I wonder if it wouldn't just be better to converge the work.

For very large tables, I can see some potential issues with storing ALL the secrets from Credstash in the cluster.  My thought was to be a bit more dynamic about things.  What I've started writing is based on the annotations found on deployments.  Instead of pulling the whole secrets table in wholesale, I thought a more viable option might be to run a pod in the kube-system namespace (and use kube2iam to grant that pod a role capable of reading from Credstash), and then create secrets based on what a given deployment has listed as needed, along with giving them an expiration field.  The planned workflow is approximately as follows:

List all deployments on the cluster, across all namespaces.  Retain any that have an annotation of "kubestash.secrets".
Loop through retained deployments.
Check for the existence, in the relevant namespace, of a secret whose name matches "kubestash-<deployment-name>".  If the secret does not exist, create it, by iterating over the list of comma-separated keys contained in the value of the annotation, and adding an expiration field of one hour from the current time.  If the secret does exist, check to see if the expiration is less than 10 minutes away, and update all individual values as well as the expiration.
List all secrets on the cluster, across all namespaces.  Retain any which begin with "kubestash-".
Loop through retained secrets.  If the secret's expiration has passed, delete the secret.

As I see it, this has a couple of inherent perks.  First of all, as credentials get updated in Credstash, they get refreshed shortly afterward in the k8s secret store, without a need to watch streams.  Second, the principle of least access is maintained by ensuring only secrets which are required are actually stored on the cluster, and only for approximately as long as they are still in use.  Third, this provides an automatic cleanup, which reduces the risk of secret leakage and prevents confusion due to an excessive number of secrets on the cluster.  And fourth, it makes secret access very auditable, because a given deployment's secrets are all in one spot.  One nice side-effect of this approach is that when you go to launch a deployment, the secrets won't yet exist, so the pod will fail to launch, but the monitoring will kick in before very long, creating the secret.  Once that occurs, the pod will launch automatically and work as normal and expected.

I realize this is a somewhat significant shift in direction from the current design, but think it could very easily be viable.  If it's not functionality you want, I can continue going down my path independently, but I think with what you have written at this point, it'd actually be a relatively easy task to add it to this project, compared with doing the same from the ground up.

**Comment by af-inet** [comment]
@isugimpy thank you for your detailed feedback & explanation !

I've read over and have been thinking about your idea for a bit, here's what I think so far:

Firstly, expiring keys is a really clever idea. I think implementing what you described would be a much more secure & flexible system.

I'll admit however, I don't personally have a use-case for it at the moment.
I think it's a fundamental trade-off between security and complexity. In your system there's more fine-grained control over how secrets are distributed at the cost of more moving parts & more per-deployment configuration.
For my use-case, I'm actually trying to minimize moving parts and minimize how much configuration is required per-deployment (we currently have over 30 deployments, maintained by different teams across the engineering department).

So that being said; I'd love to explore adding this type of functionality, but I think I'd prefer it to be optional, perhaps another command (or flag) alongside `push` and `daemon`. LMK what you think!

**Comment by isugimpy** [comment]
Glad you liked the idea!

I think what I'm going to do, as a compromise, is go ahead and fork from you for right now, write up my functionality and get it working (with a command line arg, but also with a container and manifest to support what I've described), and then open up a pull request back to you once I feel comfortable with the state of it.  If you want to accept it, that's just fine, or feel free to cherry-pick stuff back from it, or not take it at all.  :)  I'll start my company off with using my variant, and if we converge later, we can switch over to using yours.  For now, I'll close this issue.  Thanks for the response!
